POST https://localhost:7195/breakfasts/
Content-Type: application/json

{
  "name": "V",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": [
    "Oatmeal",
    "Avocado Toast",
    "Omelette",
    "Salad"
  ],
  "Sweet": [
    "Cookie"
  ]
}

###
GET https://localhost:7195/290cd041-f1dc-4a07-9759-e246265357ea