@id=f61c59bc-d350-4749-ab46-71a893130e28

PUT  https://localhost:7195/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine for God!",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": [
    "Oatmeal",
    "Avocado Toast",
    "Omelette",
    "Salad"
  ],
  "Sweet": [
    "Cookie"
  ]
}